server:
  port: 9003
spring:
  redis:
    host: 120.79.7.246
    port: 6379
  application:
    name: triangle-spit
  data:
    mongodb:
      host: 120.79.7.246
      port: 27017
      database: spitdb
  jpa:
    show-sql: true

