spring:
  application:
    name: eureka-server
server:
  port: 8762

eureka:
  instance:
    hostname: eureka-server
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false