server:
  port: 9008

spring:
  application:
    name: triangle-user

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.7.246:3306/triangle_user?characterEncoding=utf8
    password: root
    username: root
  redis:
    host: 120.79.7.246
    port: 6379
  jpa:
    show-sql: true

jwt:
  config:
    key: xupt
    ttl: 3600000

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # 跨域访问
    prefer‐ip‐address: true