server:
  port: 9001
spring:
  application:
    name: triangle‐base #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.7.246:3306/triangle_base?characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # 跨域访问
    prefer‐ip‐address: true

