server:
  port: 9009

eureka:
  client:
    service‐url:
      defaultZone: http://localhost:8761/eureka
  instance:
    # 跨域访问
spring:
  application:
    name: triangle-qa
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.79.7.246:3306/triangle_qa?characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true

feign:
  hystrix:
    enabled: true
